### ISSUE TITLE
一起学习

### ISSUE THREAD

**Issue by ccliuyang** [xukongwen/shanghan_learn#1]
看了你的整个开源的项目，少有的在github上采用python研究中医的，现在还继续开发了么

**Comment by xukongwen** [comment]
暫時沒喲了，因為想只能用notebook很不方面其他人查詢傷寒數據，現在打算做成網頁版的，但不會js，現在進展緩慢，謝謝你的關心。

**Comment by xukongwen** [comment]
> 看了你的整个开源的项目，少有的在github上采用python研究中医的，现在还继续开发了么

暫時沒喲了，因為想只能用notebook很不方面其他人查詢傷寒數據，現在打算做成網頁版的，但不會js，現在進展緩慢，謝謝你的關心。
